// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLs-z6o2Ax3r7ZFE_AwhPeSua62ukPGTc',
    appId: '1:199225720467:web:c5d863183121d6c6ccd766',
    messagingSenderId: '199225720467',
    projectId: 'task-manager-app-ea58d',
    authDomain: 'task-manager-app-ea58d.firebaseapp.com',
    storageBucket: 'task-manager-app-ea58d.firebasestorage.app',
    measurementId: 'G-5NJ7LPGVTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwSJ3diRM1qSaqYXI-4sYaGo6x-IL3gpQ',
    appId: '1:199225720467:android:3f1857c5f7702561ccd766',
    messagingSenderId: '199225720467',
    projectId: 'task-manager-app-ea58d',
    storageBucket: 'task-manager-app-ea58d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6oZylSEEUoxjLdyMJ_SPvAqcyuRth0Mo',
    appId: '1:199225720467:ios:b3d162f7f6d7c7f6ccd766',
    messagingSenderId: '199225720467',
    projectId: 'task-manager-app-ea58d',
    storageBucket: 'task-manager-app-ea58d.firebasestorage.app',
    iosBundleId: 'com.example.internshipTask',
  );
}
